const resources = [
  { title: "2024 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1UOJ3N4998R7Gb9WziLuTjG70USajC4qe/view?usp=drive_link" },
  { title: "2023 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1SqtRgJQmXPC3j5b9RQ_5XRdPVUePfimO/view?usp=drive_link" },
  { title: "2022 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1VtZz1GT4FBCUXr7ro_nMtsBtl-AjxQOu/view?usp=drive_link" },
  { title: "2021 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1RgzP_2uXQTSxnkd8q9SDEtV1CD9KxNM_/view?usp=drive_link" },
  { title: "2020 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1jtz5F7cnXaDLWMw_UlQDnVDhkAclgibn/view?usp=drive_link" },
  { title: "2019 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1HvtBoeLIq6ctep1p0BEW73M8yZb1H5lU/view?usp=drive_link" },
  { title: "2018 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/19aYdTkda8wJ1EXSRe1aW0pKS_AlGzGmn/view?usp=drive_link" },
  { title: "2017 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1hdimBpIZq8VZGAyMkvWCLANoFfA_j52Q/view?usp=drive_link" },
  { title: "2016 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1J8822yRmbLZv_tdSiI54pKjkcgPikNJ-/view?usp=drive_link" },
  { title: "2015 A/L Engineering Technology", type: "Past Paper", subject: "Engineering Technology", year: 2015, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Ff5mjT7omwdMa7naknG8ODNuVUG9rbyo/view?usp=drive_link" },

  { title: "2024 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/" },
  { title: "2023 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YCMcMALYYPDCWdhI3XD1fGVxGjjxtehl/view?usp=drive_link" },
  { title: "2022 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1CktRVMFqpd77iLPOfAbstLvqzdVR0NsH/view?usp=drive_link" },
  { title: "2021 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1RjC9qrdJfBkprgaLeRnB0JCAySl44F7x/view?usp=drive_link" },
  { title: "2020 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1qXW7ITxSnXGtSa-UkCGiMlbzt07Kg75M/view?usp=drive_link" },
  { title: "2019 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1R_dHuEQGD1x8YhuO4IdzEyKg9CG9-EVL/view?usp=drive_link" },
  { title: "2018 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_hNStbv73R53Z2wBZXCwEGZj7IX8OBex/view?usp=drive_link" },
  { title: "2017 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/16dRSEea9y1nESoLhvo1hpYOJzytfNLEk/view?usp=drive_link" },
  { title: "2016 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1bC2Bt16L8W_BFnukq231C5EiIYt9ARtV/view?usp=drive_link" },
  { title: "2015 A/L Science for Technology", type: "Past Paper", subject: "Science for Technology", year: 2015, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1QUvBaExwFFq-kc5SWcJL8NFtGp7W0ezk/view?usp=drive_link" },

  { title: "2024 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/14bJoeKfQCkigUSOxi82acDTzEjlIyAcO/view?usp=drive_link" },
  { title: "2023 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1nyEUEMjh4hVYugC121YHOA84u331EICd/view?usp=drive_link" },
  { title: "2022 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/17k9DOL5FiRupKQP8PfD6YNbFhQ7q2_eo/view?usp=drive_link" },
  { title: "2021 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1E1KrS7e4fkechTv7mFgPZ49iytliyYEi/view?usp=drive_link" },
  { title: "2020 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZqUqdiQg3pNFCfRqxV1hGIqCV4vZQonF/view?usp=drive_link" },
  { title: "2019 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1pnmgyJq60U6U9svtt9q4HfvE0olraA1C/view?usp=drive_link" },
  { title: "2018 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/15Tn_OZzVzAVmk52mbcAHw0P_IvKR902G/view?usp=drive_link" },
  { title: "2017 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1jb5MKYcwEcrXGIN01T-Gu8ZuWShWedW5/view?usp=drive_link" },
  { title: "2016 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1-TJkjjVBgBsTxP4yQGO_21imrWgmCcwh/view?usp=drive_link" },
  { title: "2015 A/L ICT Paper", type: "Past Paper", subject: "Information & Communication Technology", year: 2015, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1uVsyS8xhX_EoaPd-9-ZQp3CmO4Vakp1Y/view?usp=drive_link" },

  { title: "2025 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ANu1nlm06_F0F_9EjJ7HLAmu8Ip6YzS_/view?usp=drive_link" },
  { title: "2024 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/153rFPQy__i51xyqQuBa6ut2d7AfaFxQe/view?usp=sharing" },
  { title: "2023 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1pDKbIzfl4eMjysxQhmRmZKrn9F5rcbl5/view?usp=drive_link" },  
  { title: "2022 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1kP1bzvOseFiPjxZRnQcb6grKNsOqPi3t/view?usp=drive_link" },
  { title: "2021 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1HxUBqKEXgZ88jBQgEHZ0rfqYZTrSWQTF/view?usp=drive_link" },
  { title: "2020 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1uFJ8Fq-XBb8_TjbevQnDxSNUxKQzVEIA/view?usp=drive_link" },
  { title: "2019 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1lgWxPyYg3NJv-CHQhj17cJ8SHaW3i2Y9/view?usp=drive_link" },
  { title: "2018 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/18lCc0cB2GtTe7JHxC4d4LRIbt3JotQ86/view?usp=drive_link" },
  { title: "2017 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1vsHgEt9_fIGVS5uPu6XrntYDXuxZ3G1j/view?usp=drive_link" },
  { title: "2016 A/L BST Paper", type: "Past Paper", subject: "Bio Systems Technology", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1DYFCvtR_9y9JgGRH6XHT6LUbxgbtOfyn/view?usp=drive_link" },

  { title: "2025 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1OEN5JRzKASQXpiFKCzD3A9X6J_VQd9Hb/view?usp=drive_link" },
  { title: "2024 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1mCff_AQWqooLQve9ECBs3vyz2B22g9PN/view?usp=drive_link" },
  { title: "2023 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1UjtavMU8nShwZ-QuFDaMGF_-hSdUn-a8/view?usp=drive_link" },
  { title: "2022 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1m3bHExI5NtqMFuoK0jtS-g7UQxKcOikT/view?usp=drive_link" },
  { title: "2021 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/10SYZeMbQ3xvoa4BHH-VnLYP8D0ai04RE/view?usp=drive_link" },
  { title: "2020 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1EusZixTxbESuFJoeRpcx6NWX_Za2iHkk/view?usp=drive_link" },
  { title: "2019 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_4knXwnduUJzAn-bSbPc4hq_G44MwGch/view?usp=drive_link" },
  { title: "2018 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/13oICyL5hAFmex1T4pt1V3Roo7qSAkead/view?usp=drive_link" },
  { title: "2017 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1u1xigRj4VO8Tje3gCzIbLTZmlGcQaxo3/view?usp=drive_link" },
  { title: "2016 A/L Agri Paper", type: "Past Paper", subject: "Agricultural Science", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1k8TfLSxMYfIrHytQPjEGmFtwv2BrYuve/view?usp=drive_link" },
  // Text-Books

  { title: "SFT Physics part 1", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1vBDwewm4r6E22kGNpVTzdcLFa5ACmE_w/view?usp=drive_link" },
  { title: "SFT Physics part 2", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1rrob0pCACIPBIqp275bfVAi7wyJw8bo_/view?usp=drive_link" },
  { title: "SFT Physics part 3", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1hU6u3jeKfQItGcwWfVhoJx94QYkrrftk/view?usp=drive_link" },
  { title: "SFT Biology Book", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1xamAXDafP02VIyEj2S6k38USEERKlDJa/view?usp=drive_link" },
  { title: "SFT ICT Book", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1hAK-sp1AvmV3VI5AS0bTOFLBWIlOyhPx/view?usp=drive_link" },
  { title: "SFT Maths part 1", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/15Gg6oJRKNBnvH_cjXA1_IMe4O-rS7QXN/view?usp=drive_link" },
  { title: "SFT Physics part 1", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZfzZGuH52rXwPabJL2DUKoUEffnKZpO6/view?usp=drive_link" },
  { title: "SFT Chemestry part 1", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1DzZ-bmfQ0g3s1qmF8CNu75gcVZE3D1ar/view?usp=drive_link" },
  { title: "SFT Revision Exercies", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1EbQrQVkWrWG848QY_F5_UOBVpVUXvRGC/view?usp=drive_link" },
  { title: "SFT Bio Resources", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1l6cBDwopps8gywRVt3fiIksuAEpJq70G/view?usp=drive_link" },
  { title: "SFT Practical Book", type: "Textbook", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WH6eVNYk5tWpstwk8rghxUT_wZqSxwtm/view?usp=drive_link" },

  { title: "ET Automobile", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1dmWaVHQDT18JbNasKZsikHbyDQbkc17_/view?usp=drive_link" },
  { title: "ET Electrical Machines & Power Systems", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1dzZa5GGu4nnCovcfR_LmDCGRFjOolK3P/view?usp=drive_link" },
  { title: "ET Electronics", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1e1BDsLnWmuNBjM1n8rbBPUIxd52q4JVg/view?usp=drive_link" },
  { title: "ET Electricals", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1dq9KdDSh05vUROO3TmlM6FHx010mpwUx/view?usp=drive_link" },
  { title: "ET Entrepreneurship and Management", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1rCSLaL8NwcX_k2vizxjiNqy0vj5gSIbv/view?usp=sharing" },
  { title: "ET Drawings", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YXvW1sv1JAV3cJhdCV0k58XbC4wSAquq/view?usp=drive_link" },
  { title: "ET Civil", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1drHHqWVbhWi0qmz0Q_RdGUopOYFFWz_v/view?usp=drive_link" },
  { title: "ET Land Surveying", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1dxfu4_JPb_gxjv0RheAC9nmrL_dlLGNi/view?usp=drive_link" },
  { title: "ET Motion & the Power compression", type: "Textbook", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1QPhQvpNohHOw7_T1hNt6aJOxr29PX_Ff/view?usp=sharing" },

  { title: "ICT All lessons Part 1 (Non official)", type: "Textbook", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1xHPOYcnmrDwwIIEjas9j4TQW4qmkopGG/view?usp=drive_link" },
  { title: "ICT All lessons Part 1 (Non official)", type: "Textbook", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1XSSkuw35-D1XEBx3isHoL5Vz6TxSBrO8/view?usp=drive_link" },

  // Teachers Guide
  { title: "ET Teachers' Guide - Grade 12", type: "Teachers' Guide", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/14hLWNoDTk_Fuu-Mjk-gW8LV4ncEkcvW1/view?usp=drive_link" },
  { title: "ET Teachers' Guide - Grade 13", type: "Teachers' Guide", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1QUe6sjOSFASDsE_vH974OcS4-UG3ypi4/view?usp=sharing" },
  { title: "BST Teachers' Guide - Grade 12", type: "Teachers' Guide", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1oSnvVnA5nEFtmuQwc6NSN0niljfhac-3/view?usp=drive_link" },
  { title: "BST Teachers' Guide - Grade 13", type: "Teachers' Guide", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1EV-2GA9Qo7afN8ikoWeZwvUDQXs0IOmM/view?usp=drive_link" },
  { title: "SFT Teachers' Guide - Grade 12", type: "Teachers' Guide", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1kN9ucGhWDMBMvQT4awh7S_WafDVy7BJG/view?usp=drive_link" },
  { title: "SFT Teachers' Guide - Grade 13", type: "Teachers' Guide", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1tfeDFfF15US2X_w0oakdUZuVlOgIRECf/view?usp=drive_link" },
  { title: "Agricultural Science Teachers' Guide - Grade 12", type: "Teachers' Guide", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1LCt39P_224YkfXYSsyxoCM6Sf7Ogjhfj/view?usp=drive_link" },
  { title: "Agricultural Science Teachers' Guide - Grade 12", type: "Teachers' Guide", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1qET_mj9A8ensUMyG3P_QZI19bsStsESR/view?usp=drive_link" },
  { title: "ICT Teachers's Guide - Grade 12", type: "Teachers' Guide", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Dzy8VLoDzG6Uw5d6uf03mpcSipN2Aw9R/view?usp=drive_link" },
  { title: "ICT Teachers's Guide - Grade 13", type: "Teachers' Guide", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_4rsM484_vGV3PSZgOGX20bWL2zX6tgu/view?usp=drive_link" },

  // Model papers
  { title: "ET 2025 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1lzuGvfO4Q8ld3ysfshcUcvvXwt0FoHgC/view?usp=sharing" },
  { title: "ET 2024 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/12jlUaQmh4uMJKZRzSscSM7agUvCCuwAv/view?usp=drive_link" },
  { title: "ET 2023 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1tFHYZ0Ct1pe29G8p9fmjD16WN-4V1dx6/view?usp=drive_link" },
  { title: "ET 2022 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/14gHAUeOmdjpcYmhSv06AJifYNJEH2G3S/view?usp=drive_link" },
  { title: "ET 2021 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WCqq9dGdZAMNu-9ei5UF76_vXmfnWCRh/view?usp=drive_link" },
  { title: "ET 2020 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YWMNrQNUenPaOs2A2KVMRHEtyvIcxf4Z/view?usp=drive_link" },
  { title: "ET 2019 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/19b8cEyudRJXDJiUaTrgmRMe4ZkaBiw3o/view?usp=drive_link" },
  { title: "ET 2018 MOE Paper", type: "Model Paper", subject: "Engineering Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1W1lgkZoMcBrid60Dlxql8LE7MOgoHZ7t/view?usp=drive_link" },

  { title: "SFT 2025 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1EUP258dnpnuaQ1dwXpOXo55Cg9v0pRXc/view?usp=drive_link" },
  { title: "SFT 2024 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1O188na0II9RydfxfqC7g-LtTmA14Y8-P/view?usp=drive_link" },
  { title: "SFT 2023 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1A3RYasGxVoe02IE5ZriAN6HJa1HfSKjM/view?usp=drive_link" },
  { title: "SFT 2022 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1KVrx_3_1EScYEKS8-GaJIZJKP6ZDEwLY/view?usp=drive_link" },
  { title: "SFT 2021 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/12L3ZGOp7QmzQHWlR_P-d4cdUX-xYY8Jy/view?usp=drive_link" },
  { title: "SFT 2020 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WIUQiR9GgclFEKJjNhYQwSpp9v_a2rk2/view?usp=drive_link" },
  { title: "SFT 2019 MOE Paper", type: "Model Paper", subject: "Science for Technology", year: 2029, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/16IRNEvXu2RgzIaINWAAh0w9ocKvObQXk/view?usp=drive_link" },

  { title: "BST 2021 Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/u/4/folders/1fQyhDYWGPST0aAv9UBALB5kgXH_0saMh" },
  { title: "BST 2020 MCQ Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1-Qwe2XRimsLZkh3Y0BbrLvV1it-RFKPc/view?usp=drive_link" },
  { title: "BST 2024 MCQ Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1gXd4nlytwxlixDoe-QEYPFnqFLFlqt2m/view?usp=sharing" },
  { title: "BST 2024 Structured Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/17IOnI4NW7DBNoijcKlLVa3QkfwOBusFN/view?usp=drive_link" },
  { title: "BST 2023 MCQ Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1j_K-B3mBPiZuGJQXyJuymRXz4AhHwmYf/view?usp=drive_link" },
  { title: "BST 2023 Structured Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/15_Tf9F9u_pkbVEvAKw540BgPw6zTAL2Q/view?usp=drive_link" },
  { title: "BST 2019 MCQ Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1HlJz01MjZt5QO2N4IaFbAGoAv8johwVp/view?usp=sharing" },
  { title: "BST 2019 Structured Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1s2zjNfTBCsZVI0Da8dwVHkz1f1u76-kZ/view?usp=drive_link" },
  { title: "BST 2019 Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Ca8M_1ZTsEF3ftHhcoS0BIKRyAJzE-67/view?usp=drive_link" },
  { title: "BST  Full Model Paper 1", type: "Model Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1omqLxOuTb4M1Ts7EMmjWCYd7twaBTDhw/view?usp=sharing" },
  { title: "BST 2018 Essay Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/18Cx4EibGnPcZVFUphTgfavPibGqvEGLJ/view?usp=drive_link" },
  { title: "BST 2018 MCQ Model Paper", type: "Model Paper", subject: "Bio Systems Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1OLBoFRWJax0kxoJW2uPyUXl00_arCGK1/view?usp=sharing" },
  { title: "BST Full Model Paper 2", type: "Model Paper", subject: "Bio Systems Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/10Wf7DlDYeiutD2lUQQQLCUJVcljTMgx7/view?usp=drive_link" },
  { title: "BST Full Model Paper 3", type: "Model Paper", subject: "Bio Systems Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1jXF6UUPwDwvEyG6LmJ80teVLieyQPjgD/view?usp=sharing" },

  // Question-wise Papers

  { title: "BST වැවිලි භෝග හා සුලු අපනයන භෝග", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_TEv-99MKH6_CnCkc8BoSy6ti87ThgTB/view?usp=drive_link" },
  { title: "BST ව්‍යාපාර ස්ංවර්ධනය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1qnwYF64WqSrbAjG_sob70lL6uPED1EUn/view?usp=drive_link" },
  { title: "BST ස්වයංක්‍රියකරණය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1omocaWifZZx2CSCUhj-FzydOTHU6T4t9/view?usp=drive_link" },
  { title: "BST උද්‍යානය විද්‍යාව", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1l3dH8rerBxaTZVB0wJVJB-34R_UJHzbN/view?usp=drive_link" },
  { title: "BST යාන්ත්‍රීකරානය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/118d21V8VmY3jTk9amasSGgo544VxtwwD/view?usp=drive_link" },
  { title: "BST බිම් මැනුම සහ මට්ටම් කිරීම", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WhNAHChO0KUwwaApI8AO2ZZjMy27Etr_/view?usp=drive_link  " },
  { title: "BST පාලිත පරිසර තත්ව යටතේ භෝග් වගාව", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1QvgEWUPibN7dRMe9Ytu2gGvZW494Oqof/view?usp=drive_link" },
  { title: "BST පසු අස්වනු තාක්ශන ශිල්ප ක්‍රම", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Zdustu8kB1X_m24_E3yzq5KZgWAfuKj2/view?usp=drive_link" },
  { title: "BST පස", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1rrLi0htbthLG_mILbDF7zsRc4kDKxjMg/view?usp=drive_link" },
  { title: "BST දැවමය හා දැවමය නොවන නිෂ්පාදන", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/16k2Y_223SR3d9HtlGyDEkiQfHbMQKP8U/view?usp=drive_link" },
  { title: "BST තිරසර සංවර්ධනය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/139-G3Qmnw3TcMQrXyh754AwEH73_P67k/view?usp=drive_link" },
  { title: "BST ජෛව පද්ධති සදහ සුදුසු කාලගුණික තත්ව", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1uSqsX6dVia1UA2lr4yLs_uHIczxk9_PF/view?usp=drive_link" },
  { title: "BST ජලයේ ගුණාත්මක බව", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1l5dSUNK2BnTNJtbr3pIwYzRnMx6ZWCv-/view?usp=drive_link" },
  { title: "BST ගොවිපල සත්ව නිෂ්පාදනය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Q9ItIeAcQfx__OR6R5kZJd74C5vgRisV/view?usp=drive_link" },
  { title: "BST ගුණාත්මක පැල නිශ්පාදනය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/10t9RgGmELJhW93U89ocwOfet8TrXHBVk/view?usp=drive_link" },
  { title: "BST ගුණාත්මක ආහාර නිෂ්පාදනය", type: "Question-wise Paper", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Gd1rInzgNQxCmXPsPyNrSh_VCUgW4r7K/view?usp=drive_link" },

  { title: "SFT Area & Volume", type: "Question-wise Paper", subject: "Science for Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1qEfazMJtOvQd83HTPuD1RsFJ8nscCA5l/view?usp=drive_link" },
  { title: "SFT Chemistry", type: "Question-wise Paper", subject: "Science for Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1jeqVTB6Gip5hvT3jCPf3_IXAxvtkx_Ha/view?usp=drive_link" },
  { title: "SFT Cordinates", type: "Question-wise Paper", subject: "Science for Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/15_KBA6tjQVQweqnkZkYR79Jxd-wskhDI/view?usp=drive_link" },
  { title: "SFT Physics", type: "Question-wise Paper", subject: "Science for Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1tJ7nIF1ebtnHE30qCBGILi1dFcS-hQTb/view?usp=drive_link" },
  { title: "SFT Statistics", type: "Question-wise Paper", subject: "Science for Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1jbyIat6nEYVUdbKOkO8rm-oViL99lgnT/view?usp=drive_link" },

  { title: "ET MCQ Topic-wise Collection", type: "Question-wise Paper", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/" },
  

  { title: "ICT Programming Question Bank", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1PK19pMH6oEooHCKc8ctnBXiBMFcQ-K56/view?usp=drive_link" },
  { title: "ICT Database", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1fSlDya8pQrFZ9tBlRhne9Lyz4QArO45Y/view?usp=drive_link" },
  { title: "ICT E-Business & IOT", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1ZOvfcsDTQqbWF1mEaKH6wPBKSI4-cIpy/view?usp=drive_link" },
  { title: "ICT Logic Gate", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1sIAJ_fxYdRCrSm3CAQl_1Gdyl7PsTd0f/view?usp=drive_link" },
  { title: "ICT Networking", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1nZQyXUTN7Kmaq60SW1AELXU0N4tnUKhz/view?usp=drive_link" },
  { title: "ICT Operating System", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1E80C5mX21wuLc31k4-dU3hcN8IyGglzj/view?usp=drive_link" },
  { title: "ICT Programming", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1PK19pMH6oEooHCKc8ctnBXiBMFcQ-K56/view?usp=drive_link" },
  { title: "ICT System", type: "Question-wise Paper", subject: "Information & Communication Technology", year: 2025, medium: "English", driveUrl: "https://drive.google.com/file/d/1cvy30J-g_x0HS1ftYxfpIVQlgv46y8Sq/view?usp=drive_link" },
  


  // Province Papers
  { title: "2022 Western Province Paper 01", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YIdFJdDc62y6T0KuuY-0gQDaEaedU5qa/view?usp=drive_link" },
  { title: "2022 Western Province Paper 02", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/13dsngIpNlxlNDdQhXXXJV4moOM_MobD-/view?usp=drive_link" },
  { title: "2022 Western Province Paper 03", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1NmeXlG-ek2Ag638IyzpnkGYR8LiG61Lk/view?usp=drive_link" },
  { title: "2022 Western Province Paper 04", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YS0twv0JN9TUU5bCmnInQEM7I_5DrqHC/view?usp=drive_link" },
  { title: "2022 Western Province Paper 05", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/19LBHPuV-C9PO-KY5idpG5kNaX5iQ_xlC/view?usp=drive_link" },
  { title: "2022 North Central Province Nana Sayura", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1xaDtX5wzTT6EIZA_aPs3BXt-iBRe4xnV/view?usp=drive_link" },
  { title: "2025 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1rOPJAuymTQGBzUScT2gZWAS3DviFDTU_/view?usp=drive_link" },
  { title: "2025 Western Province Gampaha Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1PCY960o1BosF6tyrv1_tkaucv4bBXzVY/view?usp=drive_link" },
  { title: "2025 Central Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1c2yZZmKx0JvbeAg9ay41R-ZQt-wzfava/view?usp=drive_link" },
  { title: "2024 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1JfXfmxqvi2XBeFdQiJQajvyhooVWckoi/view?usp=drive_link" },
  { title: "2024 Western Province Kaluthara Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1AZ-lJiiKEmdTj_AULK-km1o8NnhNAXQC/view?usp=drive_link" },
  { title: "2023 Southern Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1nsMq-Zg9Q3ZZt_AON7rqUvgnH0nu74T8/view?usp=drive_link" },
  { title: "2023 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/17dIApdDaqpCWWsdzOYYHRFBHVNuMPG1q/view?usp=drive_link" },
  { title: "2022 Sabaragamuwa Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_2jPsW8FNG2TgSoHaLARL4SWIIcLHML3/view?usp=drive_link" },
  { title: "2022 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_DA2iN3sTQuNOrvS4iR_OhXn5uxmfd63/view?usp=drive_link" },
  { title: "2022 North Western Province Paper 2 ", type: "Province Paper", subject: "Information & Communication Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ug5eSCRCThfFRK92XshCFNKdRQlDygxQ/view?usp=drive_link" },
  { title: "2021 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZzHagDFCv_7tsi-oGCEokQh02n8hBoLG/view?usp=drive_link" },
  { title: "2020 Piliyandala Zonal Education Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1k2lZGY5MrjHnAvWuHqcoXHk4YRg7SoP1/view?usp=drive_link" },
  { title: "2020 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_kw4ONhOgzZmdN4xQbi_idI7GPvZVM5h/view?usp=drive_link" },
  { title: "2020 North Western Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1_kw4ONhOgzZmdN4xQbi_idI7GPvZVM5h/view?usp=drive_link" },
  { title: "2020 Sri Jayawardanapura Zone Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZNPYfjk6p4dfNQx92rAN-fO2dAx_WOM1/view?usp=drive_link" },
  { title: "2019 Central Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ffBJSuwgZ7NrKMICbK1-gjNb6BYwpdjc/view?usp=drive_link" },
  { title: "2018 Central Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2018, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/15VlkK8SUdgiwzC2aEpJAnxRNlKxFhFc4/view?usp=drive_link" },
  { title: "2017 Kuliyapitiya Zone Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2017, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1M3vVndzLcrvJz760F5vO9KSTbzk96uBi/view?usp=drive_link" },
  { title: "2016 Sabaragamuwa Province Paper ", type: "Province Paper", subject: "Information & Communication Technology", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1blGbmZGyBjJiyJ8yV_cRtmkJUHXDTq0i/view?usp=drive_link" },


  { title: "2024 ET Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YrxCaLSMSRUAcqvm28pd_MqfJWm2p4dY/view?usp=drive_link" },
  { title: "2024 ET Southern Province ", type: "Province Paper", subject: "Engineering Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1oHswZa1j-qq--bIeoDZI4lRthX8pDsVG/view?usp=drive_link" },
  { title: "2024 ET Central Province ", type: "Province Paper", subject: "Engineering Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Bwd3Y3MnEryGtzGmLcoIBc-UrmDUGZVG/view?usp=drive_link" },
  { title: "2023 ET Southern Province ", type: "Province Paper", subject: "Engineering Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1dVWWzI5vAGM71lK35J_1j2DBsCEdi00J/view?usp=drive_link" },
  { title: "2023 ET Sabaragamuwa Province ", type: "Province Paper", subject: "Engineering Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WpPArIdGshOYNh9P9TQgnZasHcqV82JH/view?usp=drive_link" },
  { title: "2022 ET Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YniuLDxRuA7t3_IfYSswT5YeS0sXmDFM/view?usp=drive_link" },
  { title: "2022 ET Uva Province ", type: "Province Paper", subject: "Engineering Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WqhLKWRddJdplrVFy1bNGQ-yqkbk4y7X/view?usp=drive_link" },
  { title: "2022 ET North Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1n184mx1pWkSzqIXM3qNzpdw1CKXKqtw2/view?usp=drive_link" },
  { title: "2021 ET North Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1yh1sFrBdEOFjWZlgCpifbCOyZw-B8boX/view?usp=drive_link" },
  { title: "2021 ET North Central Province ", type: "Province Paper", subject: "Engineering Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WxVkzyLUDVN8fLYw_-I5NkM7GmHrLUoX/view?usp=drive_link" },
  { title: "2021 ET Gampaha Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1IXkMg2gKgViupLbTddj0zAukIlPvEZJO/view?usp=drive_link" },
  { title: "2020 ET North Western Province ", type: "Province Paper", subject: "Engineering Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Y_hKpWEBYysqQDo2L1oiLhKAR5gHfJFo/view?usp=drive_link" },
  { title: "2019 ET Southern Province ", type: "Province Paper", subject: "Engineering Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1sYH0837w3fkOmBiQ6t_HpX853jUfP4Q7/view?usp=drive_link" },
  { title: "2019 ET Central Province ", type: "Province Paper", subject: "Engineering Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1JXB5SagQPtRPNmrXYJATJJzlSDmd43fy/view?usp=drive_link" },



  { title: "2023 SFT Southern Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1BuIqMRPhBxWGPThBq-Se2KWqe_O9RxQs/view?usp=drive_link" },
  { title: "2025 SFT Gampaha Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Cb1Lag6_EDIGIbQgj5t7uWru_l7i_tq5/view?usp=drive_link" },
  { title: "2025 SFT Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1AqaG4Af5EPX3SevuFkUaZkZtUw3wTWjq/view?usp=drive_link" },
  { title: "2024 SFT Uva Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1oHWSrabV8pkMZ-FtJ5IQuTas1sqEJm92/view?usp=drive_link" },
  { title: "2024 SFT North Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Lzb5qh4MaWD4AbehNGSTZe_CLWrduONm/view?usp=drive_link" },
  { title: "2024 SFT Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1mGw67QDyVXQZswWODsxoTB4HF1lYOHA2/view?usp=drive_link" },
  { title: "2023 SFT Uva Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Y7O2KHq0emh9o-3KUMnUac1oLRuBU3y0/view?usp=drive_link" },
  { title: "2023 SFT Southern Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1NetwGI2ZKksEtYBN-uVB5f54tySE1bw8/view?usp=drive_link" },
  { title: "2023 SFT Sabaragamuwa Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/17hFpVwF5GznWgQWZ-2W4-ZU6LJFQJrGy/view?usp=drive_link" },
  { title: "2023 SFT North Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1O_wv6RqrB_teFYgcn4O3v5nuBwORLkRB/view?usp=drive_link" },
  { title: "2022 SFT Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1AvXM9D5Da4RNK17kuwzqErmOIRNbEagL/view?usp=drive_link" },
  { title: "2022 SFT North West Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/12zdXzPtpV2EHVnV5HICrzhovrYSTqdHO/view?usp=drive_link" },
  { title: "2022 SFT Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2022, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YTzjAFDSkNaFSuqUnQABle7W95eTtkoJ/view?usp=drive_link" },
  { title: "2021 SFT North Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1uLB4SwYiXM145Z8s8HoQW0UWdw81CtMj/view?usp=drive_link" },
  { title: "2021 SFT Grade 12 North Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1jbg90iTXIMQxOKPXUgmBo2bMuty2dZxd/view?usp=drive_link" },
  { title: "2021 SFT Central Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1umL3Lv3dUqEviycFdUMa5ZRygAoMvj4k/view?usp=drive_link" },
  { title: "2020 Nalanda College Paper", type: "Province Paper", subject: "Science for Technology", year: 2020, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1cmtdghE0gMhIqdFiypYlgvSLxslcrhfI/view?usp=drive_link" },
  { title: "2024 SFT North Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1SyS41WuP7WRtsJdiSa7VSo7rmvARhxk_/view?usp=drive_link" },
  { title: "2019 SFT Sri Jayawardanapura Education zonal Paper", type: "Province Paper", subject: "Science for Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1mlQkUS_U-lIjoc0UXWGDtRwgt3sLLEQe/view?usp=drive_link" },
  { title: "2019 SFT North Western Province Paper", type: "Province Paper", subject: "Science for Technology", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1M3aBv6fDAeMgb4Oe5-npOvQ6sbogDz5t/view?usp=sharing" },
  
  { title: "2019 Agri Prototype Paper ", type: "Province Paper", subject: "Agricultural Science", year: 2019, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1x7VA_i-E6pajeynOYeWfZYHsH8ziyi1z/view?usp=drive_link" },
  { title: "2023 Agri Uva province Paper part - 2 ", type: "Province Paper", subject: "Agricultural Science", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Zj8NK79Ku5yHfGA287Zswg255SRKmOJL/view?usp=drive_link" },
  { title: "2023 Agri Western Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1fw4K04RDRjH84JBUsRzEGl4RcWp4Yheb/view?usp=drive_link" },
  { title: "2021 Agri MCQ Central Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1UdkWicIHYUtrbbGkjSgLWBJL31hlPEaS/view?usp=drive_link" },
  { title: "2024 Agri Southern Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2024, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1wXBFovgH52eo-i0OMMSOJUIJ7jk15o4X/view?usp=sharing" },
  { title: "2023 Agri North Central Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1q95JVbpj58MgHtq1P3mH8pUaufCG5bxX/view?usp=sharing" },
  { title: "2022 Agri North Central Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2016, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1duKpV60qiASxTgga2nkgoAjLDyUM9OO8/view?usp=drive_link" },
  { title: "2025 Agri North Western Province Full paper", type: "Province Paper", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YjPKXj7E8HS3RCPfxjkR01qSoCsJiM0o/view?usp=drive_link" },
  { title: "2021 Agri Sabaragamuwa Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1VfWIiJvFDcf7xQtprhxL-y8JDbrOh451/view?usp=sharing" },
  { title: "2021 Agri MCQ Uva Province Paper ", type: "Province Paper", subject: "Agricultural Science", year: 2021, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1bd3l3jv_fwk1ygA0DTIOtoMSOl0xQBls/view?usp=sharing" },
  { title: "2023 Agri Sabaragamuwa Province Paper part - 2", type: "Province Paper", subject: "Agricultural Science", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/14S1CvICsh_3TlyqjUumDBzBy3RVwby4i/view?usp=sharing" },
  { title: "2023 Agri MCQ North Western Province Paper", type: "Province Paper", subject: "Agricultural Science", year: 2023, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1TZt_56OwmWUgP2MF4MVe5nb-pLlKqDHl/view?usp=sharing" },
  



  // Extra Notes
  { title: "ET Water & Garbage Management", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1qLwhjOu3FOpk984BmSGcGHqJfMIFK4k6?usp=drive_link" },
  { title: "ET TDS", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1hluECpfAi-1vvKFLwpP-rWR6T3toPRMZ?usp=drive_link" },
  { title: "ET Safety", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1-Tw1G2GQU7ZiPwQpLycr2BipUFI09NKP?usp=drive_link" },
  { title: "ET Production", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/19BG1LpYWdqt2WhZ2tK34TYj_Y6t44YYz?usp=drive_link" },
  { title: "ET Measurments", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/18zgd6WPcmSVkCFPyzIwBGGyAWloInkUX?usp=drive_link" },
  { title: "Land Survey", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/13IQ3FdRgcN5zkdAgz2-DJzJUoKBZ_pJy?usp=drive_link" },
  { title: "ET Introduction", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1DO3ubH7FcEaWja5CWgmne9zUm-6EVU-z?usp=drive_link" },
  { title: "ET Fluids", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1nLm7nriXu_sbVJmWM-k7rISFw2Z-8Z2S?usp=drive_link" },
  { title: "ET Entrepreneurship", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/140W9C4-s0iHYdyluPXaMvkZQ2zsIjuxd?usp=drive_link" },
  { title: "ET Electronics", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1DBEGZ503K8aJ2gjUa4SpG4P1G417jxQG?usp=drive_link" },
  { title: "ET Electrical Machines", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1krVHeUxzJSIH4gHk9sa-4NF8T6V6uWa6?usp=drive_link" },
  { title: "ET Electrical", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/18k6AXE0HOyCC0nGwmvkB4prnIvpvHoZi?usp=drive_link" },
  { title: "ET Drawing", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1HI6Cxfk_tp4eC4OjsfElkVQDyD9D3IUH?usp=drive_link" },
  { title: "ET Civil", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1EG6OIxAejKFWdQL-OaOI9mHepYaAKA1k?usp=drive_link" },
  { title: "ET Motion", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1HurQD7kNAj7lFQat9R_mPotwe2yu7Dl6?usp=drive_link" },
  { title: "ET Automobile", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1Nz1JZSeyaou1rxkMV8kCt_NnSY54PxF0?usp=drive_link" },
  { title: "ET Standards and specifications", type: "Extra Notes", subject: "Engineering Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1czvZlhfRcS0WRLjZgRbv2x02vVyfP1Ac?usp=drive_link" },


  { title: "SFT Natural Products", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1wu3CWefbVZufmdlTVqO230oZqJShxqd7?usp=drive_link" },
  { title: "SFT Area and Volume", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1tNn5svuq3nXXBVoUxlv32YbKYRhQdXlt?usp=drive_link" },
  { title: "SFT Electricity", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/17P88lMfbm1Zkka_bEk4dukxEqc1MSgaA?usp=drive_link" },
  { title: "SFT Chemical Industry", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1dkw1W3WWrmZr33cnoiw7T0ifLCwE89Zr?usp=drive_link" },
  { title: "SFT Chemical Industry", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1dkw1W3WWrmZr33cnoiw7T0ifLCwE89Zr?usp=drive_link" },
  { title: "SFT Measuring Instruments", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1pJupRsmCcFcdDzvCNQPi4KhXDFpY3NK5?usp=drive_link" },
  { title: "SFT Rotational motion", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1Nq6SIUP50kaMQEmK2Q9ICrFeD-xDzdPG?usp=drive_link" },
  { title: "SFT Polymers", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/18m4nfCroCul3g5rM8ipwvbavUk2ADmvG?usp=drive_link" },
  { title: "SFT Force", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/11GIopwQDgiYFA88PHhEGmyEwKWCfwTVd?usp=drive_link" },
  { title: "SFT Enviorenment", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1JptWMQGmBPlobarwe12sKSnMmPtKW7QC?usp=drive_link" },
  { title: "SFT Computer", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1srLtTEl1leKFWvrQA9jTRYKIpXhtVutp?usp=drive_link" },
  { title: "SFT Mechanical properties of matter", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1xHZj5JcXSqGxIjiWuq7lCU0DIv4r3CbM?usp=drive_link" },
  { title: "SFT Liquidity", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/18fiuBen4NDR7Yz1t7DqnHzCoXbOscvQJ?usp=drive_link" },
  { title: "SFT Trigonometry", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1X5fzwG4oPquZuyHci4bQVEMCdjzuQoIa?usp=drive_link" },
  { title: "SFT Heat", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1NDtel-3JSwFqEYy0zttFK9ZKX93mt60k?usp=drive_link" },
  { title: "SFT Carbohydrates", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1nR4ay3oELbsFGXMsYCJARUiKslRySA-S?usp=drive_link" },
  { title: "SFT Kinetic chemistry", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1qGYCG4IiiswaRFpnl2FTPszJf8mnlSpw?usp=drive_link" },
  { title: "SFT Coordinate geometry", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1YltOZ2Ma-p8cjgS8aRa-ppCGAcpq1-wR?usp=drive_link" },
  { title: "SFT Microbiology", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1V_-u5ZGfnb6vOSyQS9C8Qpo9_x_hPACf?usp=drive_link" },
  { title: "SFT Work & Power", type: "Extra Notes", subject: "Science for Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/19jfTn8-iaDmSwcAk5256Fj13HMYYwMJk?usp=drive_link" },

  { title: "ICT Python", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1JCRLFy5j-io49MiAjIFRfMeRj0k8Ox7y?usp=drive_link" },
  { title: "ICT Php", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1YoJKs4oTzWvylFJ5LoWb43EsxRCBxojH?usp=drive_link" },
  { title: "ICT OS", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1pADPKSU_U0fwXy2M9d5Q91iVBpUQE69v?usp=drive_link" },
  { title: "ICT Number Systems", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1XXsDxY1K-vtKS_uBU8HtYOHdud15vBbd?usp=drive_link" },
  { title: "ICT Networking", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1rpqJ6-nPrc-wkuawH9z8q0Icz2tYp-L7?usp=drive_link" },
  { title: "ICT Logic Gates", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1qF2JASzwlOTR_ZTlF8XvyzwUlXz19uyv?usp=drive_link" },
  { title: "ICT IOT", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1m7ij3jewxIx0BN5M29OalWKrzerkWEgF?usp=drive_link" },
  { title: "ICT Information Systems", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1XGcKeAA7FZTesuhube9DHpYHUIWUby6T?usp=drive_link" },
  { title: "ICT Basic Concept", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1Oa2XMUQMCdxS7cL1nb6xYF8XpogdJOTz?usp=drive_link" },
  { title: "ICT HTML", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1yJuDHyBBUKspdZo9Do8i04Y3aj4khROY?usp=drive_link" },
  { title: "ICT Future Trends", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1So73uYSorP1ljEIEn_CKiH_pHcXMZqDo?usp=drive_link" },
  { title: "ICT E-commerce", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1F_PN2AN4zStaTwZKXci8tW9mEOdI3H2b?usp=drive_link" },
  { title: "ICT Database", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1ZpI4yxDjj9dTz9BPHIC3h7qggP3mB9UK?usp=drive_link" },
  { title: "ICT Computer Evolution", type: "Extra Notes", subject: "Information & Communication Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/drive/folders/1r5C-pscU3hAWZXHR1pPbS_EGlY6HzGJM?usp=drive_link" },


  { title: "Agri Lesson 1", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Py8UCMkrUB8whrsGMvn8X6S15-f1PTfL/view?usp=drive_link" },
  { title: "Agri Lesson 2", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZiMUO5imam7EAZinimo8lFdOW99ylRXh/view?usp=drive_link" },
  { title: "Agri Lesson 3", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1voIeKfsmNESrc59Daf6BWAs5-jLz7bbj/view?usp=drive_link" },
  { title: "Agri Lesson 4", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1H1Ua3CrAQ7-kvLmytf82jOTVS3bVMuBk/view?usp=drive_link" },
  { title: "Agri Lesson 5", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1g417yo-WZIFSqqWzd4rjwqQmN3jRZY_t/view?usp=drive_link" },
  { title: "Agri Lesson 6", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1ZhFm6PxSbVpGWGjIrb6Brs2NUvfK-DGF/view?usp=drive_link" },
  { title: "Agri Lesson 7", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1jlreDqFfYbkp5eZnYNBA41dBvMD8oitf/view?usp=drive_link" },
  { title: "Agri Lesson 8", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1BMoyPTMvNEVESVetO3MlDzTxRp3OJX-9/view?usp=drive_link" },
  { title: "Agri Lesson 9", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1wyLSFBifX3MBc3mp4uoO4OApA58XQZI2/view?usp=drive_link" },
  { title: "Agri Lesson 10", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1GxZclf3L2Fs39Rzransl5bLr2Z2M0c4w/view?usp=drive_link" },
  { title: "Agri Lesson 11", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Ie3IgWBKzPnTp6BLGS1xjr5-SOskaTV1/view?usp=drive_link" },
  { title: "Agri Lesson 12", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1qTkrwFio9CJyFhJ6g_pGIeFIpfYiv-qJ/view?usp=drive_link" },
  { title: "Agri Lesson 13", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1UofygMLbn3G_ytQqkAVWl8UJcfpayFKS/view?usp=drive_link" },
  { title: "Agri Lesson 14", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1wQhApBWu0U9HQKywtCyn9sCWdXqYVgxe/view?usp=drive_link" },
  { title: "Agri Lesson 15", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1WGqSTtXCHwsjE9bDXGut61WUTuCR-D2K/view?usp=drive_link" },
  { title: "Agri Lesson 16", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1wXIfZKwniXK-eURFS2t4I1jB46oxxEmP/view?usp=drive_link" },
  { title: "Agri Lesson 17", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1Q3SpJZslsdRU7ko4ExM_uhZzqMuBap_X/view?usp=drive_link" },
  { title: "Agri Lesson 18", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1XdqIbLhxZs1vQIxtc31mAtzOYMp1cptC/view?usp=drive_link" },
  { title: "Agri Lesson 19", type: "Extra Notes", subject: "Agricultural Science", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1mw6gtrpvXBEY-ZzO1DkIo7-m0-92D_nS/view?usp=drive_link" },

  { title: "BST Lesson 1", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1AJMfMa8TqtGa0e_XMxn3plmNO78Mgjp9/view?usp=drive_link" },
  { title: "BST Lesson 2", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1PUrXZ_3P4hgsrN1a25QMFive_86tGlNW/view?usp=drive_link" },
  { title: "BST Lesson 3", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1kWNQZn6ijvmVNpvZdzAAVLQwz33RFQIB/view?usp=drive_link" },
  { title: "BST Lesson 4", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1k1cD5aFDkW0FdnZZfxWAd6X4a3WHbVlm/view?usp=drive_link" },
  { title: "BST Lesson 5", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1qxFJ0m7EsriAiCiabblPdSpXlma2a-oD/view?usp=drive_link" },
  { title: "BST Lesson 6", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1OzMaFHq7b9ucOAwsUuwdSKWj9mcy0Nbn/view?usp=drive_link" },
  { title: "BST Lesson 7", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1yefhqIVUJTeLdV9Z1ZPrXuh2I2pupdFa/view?usp=drive_link" },
  { title: "BST Lesson 8", type: "Extra Notes", subject: "Bio Systems Technology", year: 2025, medium: "Sinhala", driveUrl: "https://drive.google.com/file/d/1YOIYiNW3yyvPdrbGzccSKLaEI6Ox2RsF/view?usp=drive_link" },
  
];

const universities = [
  {
    id: "UOR",
    name: "University of Ruhuna",
    shortName: "UOR",
    intro: "University of Ruhuna – එය ශ්‍රී ලංකාවේ ප්‍රධාන රාජ්‍ය විශ්වවිද්‍යාලයක් වන අතර, 1978දී ස්ථාපිත වූ අතර ප්‍රධාන පරිපාලන මධ්‍යස්ථානය Matara වේ. එහි ප්‍රධාන Faculties ලෙස Engineering, Medicine, Science, Fisheries & Marine Sciences, Allied & Health Sciences, Agriculture, Technology, Management & Finance, Humanities & Social Sciences, සහ Art යන ඒවා වේ.",
    logo: "🎓",
    colorClass: "coral",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1MpXfQ_BQqWGZaccBh0ECcBwd7wGbiRO3/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1l8Q4xq6wl6S4NOuaIrYyWo1vdnuzVCKR/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1s5ZIkehOrv6Hkly5kRdqjVZ6p5MRQIEj/view?usp=drive_link" },
    ]
  },
  {
    id: "UOJ",
    name: "University of Jaffna",
    shortName: "UOJ",
    intro: "",
    logo: "🎓",
    colorClass: "violet",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1VWoVIns_8JkyXRw8lJMOKm5RimvGwzSO/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1IX3BD7XMEdGoJxX4jENE0F_7xAzBBQR1/view?usp=drive_link" },
      
    ]
  },
  {
    id: "UOR",
    name: "University of Rajarata",
    shortName: "UOR",
    intro: "ශ්‍රී ලංකා රජරට විශ්වවිද්‍යාලය (Rajarata University of Sri Lanka) 1995 වර්ෂයේදී ස්ථාපිත කරන ලද ශ්‍රී ලංකාවේ ප්‍රමුඛ රාජ්‍ය විශ්වවිද්‍යාලයකි. එය අනුරාධපුර දිස්ත්‍රික්කයේ මිහින්තලේ ප්‍රදේශයේ පිහිටා ඇති අතර උසස් අධ්‍යාපනය, පර්යේෂණ සහ ප්‍රාදේශීය සංවර්ධනය සඳහා වැදගත් දායකත්වයක් සපයයි. මෙම විශ්වවිද්‍යාලය ප්‍රායෝගික විද්‍යා, කළමනාකරණ අධ්‍යයන, සමාජීය විද්‍යා හා මානව ශාස්ත්‍ර, කෘෂිකර්ම, වෛද්‍ය හා සහය සෞඛ්‍ය විද්‍යා සහ තාක්ෂණවේද යන පීඨවලින් සමන්විත වේ. විවිධ අධ්‍යයන ක්ෂේත්‍ර ඔස්සේ දැනුම, කුසලතා සහ නවෝත්පාදන වර්ධනය කිරීම සඳහා කැපවී සිටින මෙම විශ්වවිද්‍යාලය ශ්‍රී ලංකාවේ උසස් අධ්‍යාපන පද්ධතියේ වැදගත් ස්ථානයක් දරයි.",
    logo: "🎓",
    colorClass: "Yellow",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/14FGLoIhGM4VR_rAZwpA-XbQlgkJB6D0V/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1Xm_lzY2hbgtJcZBYJw1dQtue1woje5Yz/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1O9qtfs2C5iTRdphEIPTV8zD2jgbttqLP/view?usp=drive_link" },
    ]
  },
  {
    id: "UOS",
    name: "University of SEUSL",
    shortName: "UOS",
    intro: "",
    logo: "🎓",
    colorClass: "mint",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1C1yu81yY2hh0RflEjnwsbcSrWIYVBfsc/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1mC7X6cXuO1x2ispen7dD5QFroZUNEIzm/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1b2-aInaI_znxtnZFBK1AHQ6PFP4sOmX7/view?usp=drive_link" },
    ]
  },
  {
    id: "UOW",
    name: "University of Wayaba",
    shortName: "UOW",
    intro: "ශ්‍රී ලංකා වයඹ විශ්වවිද්‍යාලය (Wayamba University of Sri Lanka) 1999 වර්ෂයේදී ස්ථාපිත කරන ලද ශ්‍රී ලංකාවේ ප්‍රමුඛ රාජ්‍ය විශ්වවිද්‍යාලයකි. එය කුලියාපිටිය සහ මාකඳුර යන ප්‍රදේශ දෙකේ පිහිටි පරිශ්‍රවලින් සමන්විත වන අතර උසස් අධ්‍යාපනය, පර්යේෂණ සහ නවෝත්පාදන සඳහා වැදගත් දායකත්වයක් සපයයි. මෙම විශ්වවිද්‍යාලය කෘෂිකර්ම හා වැවිලි කළමනාකරණ, ප්‍රායෝගික විද්‍යා, ව්‍යාපාර අධ්‍යයන හා මූල්‍ය, පශු සම්පත්, ධීවර හා පෝෂණ, තාක්ෂණවේද සහ වෛද්‍ය යන පීඨවලින් සමන්විත වේ. ප්‍රායෝගික දැනුම සහ වෘත්තීය කුසලතා වර්ධනය කිරීම තුළින් රටේ සමාජීය හා ආර්ථික සංවර්ධනයට දායක වන උපාධිධාරීන් බිහිකිරීම මෙම විශ්වවිද්‍යාලයේ ප්‍රධාන අරමුණකි.",
    logo: "🎓",
    colorClass: "coral",
    courses: [
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/13gq-Av2tY1S4tJW3IlkIWIJc1G9I9EaP/view?usp=drive_link" },
      
    ]
  },
  {
    id: "UOC",
    name: "University of Colombo",
    shortName: "UOC",
    intro: "කොළඹ විශ්වවිද්‍යාලය (University of Colombo) ශ්‍රී ලංකාවේ පැරණිතම සහ ප්‍රමුඛතම රාජ්‍ය විශ්වවිද්‍යාලයන්ගෙන් එකක් වන අතර, ප්‍රධාන විශ්වවිද්‍යාලයක් ලෙස 1921 වර්ෂයේදී ස්ථාපිත විය. එය කොළඹ නගරයේ පිහිටා ඇති අතර කලා, අධ්‍යාපන, නීති, කළමනාකරණ හා මූල්‍ය, වෛද්‍ය, විද්‍යා, තාක්ෂණවේද, හෙද සහ පශ්චාත් උපාධි යන පීඨ රැසකින් සමන්විත වේ. එසේම, ශ්‍රී ලංකා පරිගණක අධ්‍යයනායතනය (UCSC) ද මෙම විශ්වවිද්‍යාලයට අනුබද්ධව ක්‍රියාත්මක වන අතර, තොරතුරු තාක්ෂණ සහ පරිගණක අධ්‍යයන ක්ෂේත්‍රයේ ප්‍රමුඛ අධ්‍යාපනික ආයතනයක් ලෙස සැලකේ.",
    logo: "🏛️",
    colorClass: "violet",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1-lRZwQDTIyItWbRk92MlT9S2evXRBd-L/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1kvV7RIfNRIwk4doXAdmTe4buEqL-93ND/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1zog0ipGjOqVYCtDre28WcQlgExt3RqjN/view?usp=drive_link" },
    ]
  },
  {
    id: "USJ",
    name: "University of Sri Jayewardenepura",
    shortName: "USJ",
    intro: "ශ්‍රී ජයවර්ධනපුර විශ්වවිද්‍යාලය (University of Sri Jayewardenepura) 1959 වර්ෂයේදී  විශ්වවිද්‍යාලය ලෙස ආරම්භ වූ ශ්‍රී ලංකාවේ ප්‍රමුඛ රාජ්‍ය විශ්වවිද්‍යාලයකි. එය ගංගොඩවිල, නුගේගොඩ ප්‍රදේශයේ පිහිටා ඇති අතර මානව ශාස්ත්‍ර හා සමාජීය විද්‍යා, ප්‍රායෝගික විද්‍යා, කළමනාකරණ අධ්‍යයන හා වාණිජ්‍ය, වෛද්‍ය විද්‍යා, තාක්ෂණවේද, ඉංජිනේරු, සහය සෞඛ්‍ය විද්‍යා, දන්ත වෛද්‍ය, නාගරික හා ජලජ ජීව සම්පත් සහ පශ්චාත් උපාධි යන පීඨවලින් සමන්විත වේ. අධ්‍යාපනය, පර්යේෂණ සහ නවෝත්පාදන ක්ෂේත්‍රවල විශිෂ්ටත්වය සඳහා ප්‍රසිද්ධ මෙම විශ්වවිද්‍යාලය ශ්‍රී ලංකාවේ උසස් අධ්‍යාපන ක්ෂේත්‍රයේ වැදගත් ස්ථානයක් හිමි කරගෙන ඇත.",
    logo: "🦁",
    colorClass: "yellow",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1W2e1FPhW7tZeQQlnJh9L2OJ3Xr-bBG01/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1U5DHpOiYsrdaqalabgmblZSqrdyH-6dD/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1VK0zDrmETD7EVR_UooCYh4EP8tWOTPDJ/view?usp=drive_link" },
    ]
  },
  {
    id: "UOK",
    name: "University of Kelaniya",
    shortName: "UOK",
    intro: "කැලණිය විශ්වවිද්‍යාලය (University of Kelaniya) 1959 වර්ෂයේදී විද්‍යාලංකාර විශ්වවිද්‍යාලය ලෙස ආරම්භ වූ අතර, ශ්‍රී ලංකාවේ ප්‍රමුඛ රාජ්‍ය විශ්වවිද්‍යාලයන්ගෙන් එකකි. එය ගම්පහ දිස්ත්‍රික්කයේ කැලණිය ප්‍රදේශයේ පිහිටා ඇති අතර උසස් අධ්‍යාපනය, පර්යේෂණ සහ සමාජ සේවාවන් සඳහා වැදගත් දායකත්වයක් සපයයි. මෙම විශ්වවිද්‍යාලය මානව ශාස්ත්‍ර, සමාජීය විද්‍යා, වාණිජ හා කළමනාකරණ අධ්‍යයන, විද්‍යා, වෛද්‍ය, පරිගණක හා තාක්ෂණ, පශ්චාත් උපාධි අධ්‍යයන ඇතුළු විවිධ පීඨවලින් සමන්විත වේ. ගුණාත්මක අධ්‍යාපනය සහ නවෝත්පාදන පර්යේෂණ තුළින් දේශීය හා ජාත්‍යන්තර වශයෙන් දක්ෂ උපාධිධාරීන් බිහිකිරීම සඳහා මෙම විශ්වවිද්‍යාලය කැපවී සිටී.",
    logo: "🍃",
    colorClass: "mint",
    courses: [
     { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1-TX1yVZVwlD_PKesMXpdxXXHZwrv-13h/view?usp=drive_link" },
     { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/11Bpzd1B4TaMOop6hyo8aEMccSl29Vm8d/view?usp=drive_link" },
     { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1ue8uqzIfORVLFn0qiT1dUr450ZPpVn8i/view?usp=drive_link" },
    ]
  },
  {
    id: "UOS",
    name: "University of Sabaragamuwa",
    shortName: "UOS",
    intro: "ශ්‍රී ලංකා සබරගමුව විශ්වවිද්‍යාලය (Sabaragamuwa University of Sri Lanka) 1995 වර්ෂයේදී ස්ථාපිත කරන ලද ශ්‍රී ලංකාවේ ප්‍රමුඛ රාජ්‍ය විශ්වවිද්‍යාලයකි. එය බෙලිහුල්ඔය ප්‍රදේශයේ පිහිටා ඇති අතර උසස් අධ්‍යාපනය, පර්යේෂණ සහ ප්‍රාදේශීය සංවර්ධනය සඳහා වැදගත් දායකත්වයක් සපයයි. මෙම විශ්වවිද්‍යාලය කෘෂිකාර්මික විද්‍යා, ප්‍රායෝගික විද්‍යා, භූමාතික, කළමනාකරණ අධ්‍යයන, සමාජීය විද්‍යා හා භාෂා, වෛද්‍ය සහ තාක්ෂණවේද යන පීඨවලින් සමන්විත වේ. විවිධ විෂය ක්ෂේත්‍ර ඔස්සේ ගුණාත්මක අධ්‍යාපනය ලබාදෙමින්, රටේ සමාජීය හා ආර්ථික සංවර්ධනයට දායක වන වෘත්තීයවේදීන් සහ පර්යේෂකයන් බිහිකිරීම සඳහා මෙම විශ්වවිද්‍යාලය කැපවී සිටී.",
    logo: "🏔️",
    colorClass: "sky",
    courses: [
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1mC7X6cXuO1x2ispen7dD5QFroZUNEIzm/view?usp=drive_link" },
      
    ]
  },
  {
    id: "UWU",
    name: "Uva Wellassa University",
    shortName: "UWU",
    intro: "ඌව වෙල්ලස්ස විශ්වවිද්‍යාලය (Uva Wellassa University) 2005 වර්ෂයේදී ස්ථාපිත කරන ලද ශ්‍රී ලංකාවේ නවීන රාජ්‍ය විශ්වවිද්‍යාලයකි. එය බදුල්ල නගරයේ පිහිටා ඇති අතර දැනුම, නවෝත්පාදන සහ වෘත්තීය කුසලතා සංවර්ධනය කෙරෙහි විශේෂ අවධානයක් යොමු කරයි. මෙම විශ්වවිද්‍යාලය විද්‍යා හා තාක්ෂණ, කළමනාකරණ, සත්ව විද්‍යා හා අපනයන කෘෂිකර්ම සහ තාක්ෂණ අධ්‍යයන යන පීඨවලින් සමන්විත වේ. ප්‍රායෝගික අධ්‍යාපනය හා කර්මාන්ත අවශ්‍යතා සමඟ සම්බන්ධිත ඉගෙනුම් අවස්ථා ලබාදෙමින්, රටේ ආර්ථික හා සමාජ සංවර්ධනයට දායක වන උපාධිධාරීන් බිහිකිරීම මෙම විශ්වවිද්‍යාලයේ ප්‍රධාන අරමුණකි.",
    logo: "💎",
    colorClass: "pink",
    courses: [
      { name: "BBST Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1N1S4Kff_dxlll9P1xeYxQDAhVi_bGgQN/view?usp=drive_link" },
      { name: "BET Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/11mHM3TwzgANNkRmZNc-VTQZCXasbFzsN/view?usp=drive_link" },
      { name: "BICT Course in Faculty of Technology", driveUrl: "https://drive.google.com/file/d/1B-CISXxpFWcTXqg9liGXRu2zYc3C-NQP/view?usp=drive_link" },
    ]
  }
];
